### PR TITLE
Google Auth in a working state; removed Facebook auth altogether

### PR DESCRIPTION
**Pull request by cyprusad**
Basic google oauth works. Nothing fancy. Removed Facebook auth since facebook accounts can get compromised. `@exmna.org` email accounts on the other hand can be revoked by admin if compromised.

@miranmirza @EmilyMB

### CODE REVIEW

**Comment by miranmirza** [comment]
👍

**Comment by miranmirza** [comment]
The tests failed, not sure if we were testing login via facebook (which might've caused them to fail)

**Comment by cyprusad** [comment]
Ugh, I don't know what I am doing with `rspec` and its taking too long to fix. Removing concerned tests, punting the figuring out of tests for the future.

**Comment by EmilyMB** [comment]
@cyprusad @miranmirza Sorry I was out of town without internet :sun_with_face: :ocean: I'll work on modifying the tests so they can function with the new auth stuff.

**Pull request merged**
